puts "Destroy previous Kitas"
Kindergarden.destroy_all
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


kindergardens = Kindergarden.create([{name: "Sunshine Kita", address: "Leopoldstraße 50, Berlin", language: "English-German", capacity: 200, is_available: true, email: "info@sunshine.de", phone: "5047385949", photo: "https://images.unsplash.com/photo-1564429238817-393bd4286b2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "08:00", closing_hours: "18:00", size: "more than 50", age_structure: "Mixed ages", edu_system: "Emmy Picker", aesthetic_edu: "Health"},
          {name: "Meine Erste Kita", address: "Brandenburgische Straße 22, Berlin", language: "English-German", capacity: 84, is_available: true, email: "info@mek.de", phone: "5028758789", photo: "https://images.unsplash.com/photo-1567746455504-cb3213f8f5b8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "08:00", closing_hours: "17:00", size: "more than 50", age_structure: "Mixed ages", edu_system: "Fröbel", aesthetic_edu: "Intercultural Edu."},
          {name: "Charlotte", address: "Genslerstraße 21, Berlin", language: "German", capacity: 120, is_available: false, email: "charlotte@charlottekita.de", phone: "5073478346", photo: "https://images.unsplash.com/flagged/photo-1551887373-6edba6dacbb1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "08:00", closing_hours: "19:00", size: "more than 50", age_structure: "Mixed ages", edu_system: "Situational", aesthetic_edu: "Natural and Environment"},
          {name: "Tutti Amici", address: "Leopoldßtraße 82, Berlin", language: "Italian-German", capacity: 64, is_available: true, email: "info@tuttiamici.com", phone: "5038974983", photo: "https://images.unsplash.com/photo-1541692641319-981cc79ee10a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "09:00", closing_hours: "18:00", size: "less than 50", age_structure: "Mixed ages", edu_system: "Montessory", aesthetic_edu: "Theater Education"},
          {name: "Le Tour Eiffel", address: "Holteistraße 18, Berlin", language: "French-German", capacity: 35, is_available: false, email: "letour@lte.de", phone: "5079834224", photo: "https://images.unsplash.com/flagged/photo-1550706468-bedf630a1985?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "09:00", closing_hours: "19:00", size: "more than 50", age_structure: "Mixed ages", edu_system: "Freinet", aesthetic_edu: "Body and Movement"},
          {name: "Detsky Sad Kita", address: "Weisbachstraße 1-4, Berlin", language: "Russian-German", capacity: 65, is_available: false, email: "info@detskysk.com", phone: "64872634", photo: "https://images.unsplash.com/photo-1554721299-e0b8aa7666ce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "06:00", closing_hours: "16:00", size: "more than 50", age_structure: "Old homogenous", edu_system: "Open Work", aesthetic_edu: "Disabilitiy Integr."},
          {name: "Stesti Kita", address: "Schulweg, Berlin", language: "Czech-German", capacity: 25, is_available: false, email: "info@stestikita.de", phone: "5083275892", photo: "https://images.unsplash.com/photo-1544780631-d7cc800ef62d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "06:00", closing_hours: "17:00", size: "more than 50", age_structure: "Nest group", edu_system: "Reggio", aesthetic_edu: "Health"},
          {name: "Boldog Gyerekek Kita", address: "Lichtenberger Straße, Berlin", language: "Hungarian-German", capacity: 46, is_available: true, email: "info@bgk.de", phone: "50235436", photo: "https://images.unsplash.com/photo-1564429097439-e400382dc893?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "10:00", closing_hours: "20:00", size: "less than 50", age_structure: "Mixed ages", edu_system: "Waldorf", aesthetic_edu: "Health"},
          {name: "Happikizzu", address: "Jacobystraße 5-6, Berlin", language: "Japanese-German", capacity: 38, is_available: true, email: "hattori@happikizzu.de", phone: "502343523", photo: "https://images.unsplash.com/flagged/photo-1570319736696-894f69f52bd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", opening_hours: "07:00", closing_hours: "17:00", size: "more than 50", age_structure: "Nest group", edu_system: "Open Work", aesthetic_edu: "Health"},
          {name: "Szczescie", address: "Bornholmer Straße 2, Berlin", language: "Polish-German", capacity: 52, is_available: true, email: "info@polishkitaberlin.de", phone: "5023423467", photo: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60", opening_hours: "07:00", closing_hours: "18:00", size: "more than 50", age_structure: "Old homogenous", edu_system: "Open Work", aesthetic_edu: "Scientific experience"}])

